#!/usr/bin/env python3
"""The decision pipeline: one card per held-back site, built only from components that survived the
reliability checks (docs/decision.md).

  call         fingerprint (16 arrangement features, conformal NB) = the only model with a significant LOSO
               result; cross-checked by XGBoost on all reliable features and by the method consensus.
  confidence   fingerprint credibility / confidence, XGBoost posterior, consensus share.
  inside B3?   fingerprint conformal p_Batch_3, joint family percentiles vs the Batch 3 baseline.
  why          KPIs off beyond the field's own sampling noise (deviation table), Si depth profile,
               SOC-1 pore loss vs Batch 3 (the FEM-validated consequence).

Writes outputs/decision/heldout_decisions.csv, heldout_cards.md, figures/decision.png.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
O = ROOT / "outputs"
OUT = O / "decision"
BATCHES = ["Batch_1", "Batch_2", "Batch_3"]
HELD = ["3e122cbj", "fn0mhxef", "xrv9xvzb"]
NAMES = {
    "K01_si_frac_adm": "Si area fraction", "K02_si_density_per_1000um2": "Si number density",
    "K03_ecd_d50_um": "Si size d50", "K03_ecd_d90_um": "Si size d90", "K03_ecd_max_um": "largest Si object",
    "K05_voronoi_sigma": "Voronoi cell spread", "K09_mst_m_norm": "MST edge (spacing)",
    "K09_mst_sigma_norm": "MST edge spread", "K14_empty_p95_um": "empty-space p95",
    "K15_si_graphite_contact_frac": "Si–graphite contact", "F02_soc100_pore_loss": "SOC-1 pore loss",
}


def rd(p: str) -> pd.DataFrame:
    return pd.read_csv(O / p, dtype={"batch": str, "site": str})


def main() -> int:
    OUT.mkdir(exist_ok=True)
    (OUT / "figures").mkdir(exist_ok=True)
    fp = rd("fingerprint/heldout_predictions.csv").set_index("site")
    xg = rd("xgb/heldout_predictions.csv")
    xg = xg[xg.family == "all_reliable"].set_index("site")
    cons = rd("crosswalk/heldout_consensus.csv")
    joint = rd("acceptance/heldout_joint.csv")
    dev = rd("acceptance/deviation_long.csv")
    dev["site"] = dev.field.str.split("/").str[1]
    fpf = pd.concat([rd("fingerprint/features.csv"), rd("fingerprint/heldout_features.csv")]).set_index("site")
    fu = pd.concat([rd("functional/site_functional.csv"), rd("functional/heldout_site_functional.csv")]).set_index("site")
    dsw = rd("functional/depth_swelling.csv")
    b3 = fu[fu.batch == "Batch_3"]

    rows, cards = [], ["# Held-back site decisions\n",
                       "Generated by `scripts/run_decision.py`; method in `docs/decision.md`. Batch 3 is the supplier baseline.\n"]
    for s in HELD:
        f = fp.loc[s]
        x = xg.loc[s]
        c = cons[(cons.site == s) & cons.call.isin(BATCHES)]
        agree = int((c.call == f.assigned).sum())
        j = joint[joint.site == s].set_index("family")
        off = dev[(dev.site == s) & (dev.flag == "off") & dev.kpi.isin(NAMES)].sort_values("robust_z", key=np.abs, ascending=False)
        noise = dev[(dev.site == s) & (dev.flag == "within_sampling_noise")]
        pl = float(fu.loc[s, "F02_soc100_pore_loss"])
        pl_pct = float((b3.F02_soc100_pore_loss < pl).mean() * 100)
        d = dsw[dsw.site == s].sort_values("band")
        prof = d.F02_pore_loss.to_numpy()
        prof_rel = prof / prof.mean()
        mid = fpf.loc[s, "si_depth_mid_dip"]
        row = dict(site=s, call=f.assigned, fingerprint_credibility=f.credibility, fingerprint_confidence=f.confidence,
                   fingerprint_p_batch3=f.p_Batch_3, xgb_call=x.assigned,
                   xgb_p_call=float(x[f"p_{f.assigned}"]), xgb_p_batch3=float(x.p_Batch_3),
                   consensus=f"{agree}/{len(c)}",
                   kpi_pct_vs_b3=float(j.loc["kpi_v1", "pct_among_B3_loo"]),
                   fingerprint_pct_vs_b3=float(j.loc["fingerprint", "pct_among_B3_loo"]),
                   functional_pct_vs_b3=float(j.loc["functional", "pct_among_B3_loo"]),
                   n_kpis_off=int(len(off)), kpis_off=";".join(off.kpi),
                   pore_loss_soc1=pl, pore_loss_pct_vs_b3=pl_pct, si_depth_mid_dip=float(mid),
                   pore_loss_depth_profile_rel=";".join(f"{v:.2f}" for v in prof_rel))
        rows.append(row)

        inside = "inside" if f.p_Batch_3 > 0.1 and row["kpi_pct_vs_b3"] < 95 and row["functional_pct_vs_b3"] < 95 else "outside"
        cards.append(f"\n## {s} → **{f.assigned.replace('_', ' ')}**\n")
        cards.append(f"- **Confidence**: fingerprint credibility {f.credibility:.2f}, confidence {f.confidence:.2f}; "
                     f"XGBoost (all reliable features) P({f.assigned.replace('_', ' ')}) = {row['xgb_p_call']:.2f}; "
                     f"{agree} of {len(c)} independent methods agree.")
        cards.append(f"- **Inside the Batch 3 baseline?** {inside.capitalize()}. Conformal p(Batch 3) = {f.p_Batch_3:.2f}; "
                     f"percentile among Batch 3 fields: composition {row['kpi_pct_vs_b3']:.0f}, arrangement "
                     f"{row['fingerprint_pct_vs_b3']:.0f}, function {row['functional_pct_vs_b3']:.0f}.")
        if len(off):
            parts = [f"{NAMES[r.kpi]} {r.robust_z:+.1f} robust SD ({r.dev_over_sampling_sd:.0f}× its sampling SD)"
                     for r in off.itertuples()]
            cards.append("- **How it differs from Batch 3 (beyond measurement noise)**: " + "; ".join(parts) + ".")
        else:
            extra = (f" {len(noise)} large-looking deviation(s) fall within the field's own sampling noise."
                     if len(noise) else "")
            cards.append("- **How it differs from Batch 3 (beyond measurement noise)**: no reliable KPI is off." + extra +
                         " The call rests on arrangement, not composition.")
        cards.append(f"- **Arrangement**: Si depth mid-dip {mid:+.2f} (Batch 2 median ≈ −0.9, Batch 3 ≈ −0.1); "
                     f"SOC-1 pore-loss depth profile (top→bottom, relative to mean) {', '.join(f'{v:.2f}' for v in prof_rel)}.")
        cards.append(f"- **Lithiation consequence**: SOC-1 geometric pore loss {pl:.2f} = {pl_pct:.0f}th percentile of Batch 3 "
                     f"(predicts FEM pore closure, ρ 0.73).")
    D = pd.DataFrame(rows)
    D.to_csv(OUT / "heldout_decisions.csv", index=False)
    (OUT / "heldout_cards.md").write_text("\n".join(cards) + "\n")

    fig, axes = plt.subplots(1, 3, figsize=(13, 3.8))
    for ax, s in zip(axes, HELD):
        f, x = fp.loc[s], xg.loc[s]
        w = 0.38
        ax.bar(np.arange(3) - w / 2, [f[f"p_{b}"] for b in BATCHES], w, label="fingerprint conformal p", color="#777")
        ax.bar(np.arange(3) + w / 2, [x[f"p_{b}"] for b in BATCHES], w, label="XGBoost posterior", color="#1f77b4")
        ax.set_xticks(range(3), ["B1", "B2", "B3"])
        ax.set_ylim(0, 1.05)
        r = D[D.site == s].iloc[0]
        ax.set_title(f"{s} → {f.assigned.replace('_', ' ')}\nconsensus {r.consensus}, KPIs off: {r.n_kpis_off}, "
                     f"pore loss pct vs B3: {r.pore_loss_pct_vs_b3:.0f}", fontsize=9)
    axes[0].legend(fontsize=8, frameon=False)
    fig.suptitle("Held-back decisions: conformal p (membership) vs posterior (assignment)", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "figures" / "decision.png", dpi=150)
    print((OUT / "heldout_cards.md").read_text())
    return 0


if __name__ == "__main__":
    sys.exit(main())
